### ISSUE TITLE
Ultimaker S5 7.1.3 safetotouch + cooldown not compatible

### ISSUE THREAD

**Issue by sparky002** [SmithyAT/UltiTuner#2]
Hi,
I am on 7.1.3 on an Ultimaker S5. The active leveling and reboot command works but I can not adjust safetotouch or cooldown.
Ultimaker might have changed this terminology in 7.1.3?

This is the message print out in terminal.
"Checking printer/firmware compatibility.....done, but not compatible"

Thanks

**Comment by SmithyAT** [comment]
Hi
the error message is a bit outdated and not 100% correct. The problem is that, you are right, UM has changed the behavior with the firmware. So the parameters I am looking for during executing these commands are not there anymore.

But the good news are, that you don't need the hack anymore for the cooldown/safetotouch, because UM has implemented a feature to skip the cooldown.

From the firmware release notes:
Skip cooldown. At the end of a print (when finished or aborted), the Confirm removal option will be available immediately, without waiting for the build plate to cool down. This improves the end-of-print workflow and allows the next print job to be started faster.
https://support.ultimaker.com/hc/en-us/articles/360012055979

I have to adopt the error message a bit, that it is clear. Maybe telling something like, it is obsolete with the firmware or something like that.
