### ISSUE TITLE
Firmware 8.2.1 compatibility

### ISSUE THREAD

**Issue by mspinolaeie** [SmithyAT/UltiTuner#6]
I have an S5 with firmware 8.2.1. Ultituner returns a "firmware non compatible" message. Any chance it will be updated to support this firmware?

**Comment by SmithyAT** [comment]
Which command are you trying?
The return message can be a bit confusing. There is no global check if a specific firmware is supported or not, it depends on the command you are using and if the specific part is not found in the firmware, "firmware non compatible" message is returned.

If your commands were safetotouch or cooldown, then it is correct, these commands are not working anymore since 7.1 because UM changed the firmware to not check the bed temperature anymore. So with firmware 7.1 or higher you don't need to modify it, because the printer doesn't wait anymore.

Here are some more infos:
https://community.ultimaker.com/topic/39188-ultituner-a-tool-to-tweak-your-printer/?do=findComment&comment=311944

**Comment by mspinolaeie** [comment]
Thank you very much. That were actually the commands.
